CREATE TABLE Cities (
  Id INT PRIMARY KEY IDENTITY,
  Name NVARCHAR(20) NOT NULL,
  CountryCode CHAR(2) NOT NULL
)

CREATE TABLE Hotels (
  Id INT PRIMARY KEY IDENTITY,
  Name NVARCHAR(30) NOT NULL,
  CityId INT NOT NULL FOREIGN KEY REFERENCES Cities (Id),
  EmployeeCount INT NOT NULL,
  BaseRate DECIMAL(15, 2)
)

CREATE TABLE Rooms (
  Id INT PRIMARY KEY IDENTITY,
  PRICE DECIMAL(15, 2) NOT NULL,
  TYPE NVARCHAR(20) NOT NULL,
  Beds INT NOT NULL,
  HotelId INT NOT NULL FOREIGN KEY REFERENCES Hotels (Id)
)

CREATE TABLE Trips (
  Id INT PRIMARY KEY IDENTITY,
  RoomId INT NOT NULL FOREIGN KEY REFERENCES Rooms (Id),
  BookDate DATE NOT NULL,
  ArrivalDate DATE NOT NULL,
  ReturnDate DATE NOT NULL,
  CancelDate DATE,

  CONSTRAINT CHK_Trips_BookDate CHECK (datediff(DAY, BookDate, ArrivalDate) > 0),
  CONSTRAINT CHK_Trips_ArrivalDate CHECK (datediff(DAY, ArrivalDate, ReturnDate) > 0)
)

CREATE TABLE Accounts (
  Id INT PRIMARY KEY IDENTITY,
  FirstName NVARCHAR(50) NOT NULL,
  MiddleName NVARCHAR(20),
  LastName NVARCHAR(50) NOT NULL,
  CityId INT NOT NULL FOREIGN KEY REFERENCES Cities (Id),
  BirthDate DATE NOT NULL,
  Email VARCHAR(100) NOT NULL UNIQUE
)

CREATE TABLE AccountsTrips (
  AccountId INT NOT NULL FOREIGN KEY REFERENCES Accounts (Id),
  TripId INT NOT NULL FOREIGN KEY REFERENCES Trips (Id),
  Luggage INT NOT NULL CHECK (Luggage >= 0)

    CONSTRAINT PK_AccountsTrips PRIMARY KEY (AccountId, TripId)
)